import { v4 as uuidv4 } from 'uuid';
import type { Caso } from '../types.js';

export const seedCasos: Caso[] = [
  {
    id: uuidv4(),
    nombre: '🔴 Error crítico en login',
    descripcion: 'Los usuarios no pueden iniciar sesión con redes sociales',
    estado: 'nuevo',
    prioridad: 'alta',
    responsable: 'Juan Pérez',
  },
  {
    id: uuidv4(),
    nombre: '🟡 Mejorar UI del dashboard',
    descripcion: 'Hacer la interfaz más moderna y responsiva',
    estado: 'en progreso',
    prioridad: 'media',
    responsable: 'María García',
  },
  {
    id: uuidv4(),
    nombre: '🟢 Documentar API REST',
    descripcion: 'Crear documentación completa de todos los endpoints',
    estado: 'completado',
    prioridad: 'baja',
    responsable: undefined,
  },
  {
    id: uuidv4(),
    nombre: '🔵 Implementar búsqueda global',
    descripcion: 'Agregar barra de búsqueda en el dashboard',
    estado: 'nuevo',
    prioridad: 'media',
    responsable: 'Carlos López',
  },
  {
    id: uuidv4(),
    nombre: '⚪ Optimizar base de datos',
    descripcion: 'Revisar índices y queries lentos',
    estado: 'nuevo',
    prioridad: 'baja',
    responsable: undefined,
  },
  {
    id: uuidv4(),
    nombre: '🟠 Integrar notificaciones push',
    descripcion: 'Permitir notificaciones en tiempo real para eventos importantes',
    estado: 'en progreso',
    prioridad: 'alta',
    responsable: 'Ana Torres',
  },
  {
    id: uuidv4(),
    nombre: '🟣 Revisar seguridad de endpoints',
    descripcion: 'Auditar y reforzar la seguridad de la API',
    estado: 'nuevo',
    prioridad: 'alta',
    responsable: 'Luis Ramírez',
  },
  {
    id: uuidv4(),
    nombre: '🟤 Migrar a nueva versión de Node.js',
    descripcion: 'Actualizar el entorno a Node.js 20.x',
    estado: 'en progreso',
    prioridad: 'media',
    responsable: 'Sofía Méndez',
  },
  {
    id: uuidv4(),
    nombre: '🟥 Corregir errores de validación en formularios',
    descripcion: 'Algunos campos no muestran mensajes de error correctamente',
    estado: 'nuevo',
    prioridad: 'alta',
    responsable: undefined,
  },
  {
    id: uuidv4(),
    nombre: '🟩 Añadir soporte multilenguaje',
    descripcion: 'Permitir cambiar el idioma de la interfaz',
    estado: 'nuevo',
    prioridad: 'media',
    responsable: 'Pedro Castillo',
  },
  {
    id: uuidv4(),
    nombre: '🟦 Mejorar accesibilidad',
    descripcion: 'Asegurar que la app sea usable con lectores de pantalla',
    estado: 'en progreso',
    prioridad: 'media',
    responsable: undefined,
  },
  {
    id: uuidv4(),
    nombre: '🟧 Implementar exportación a Excel',
    descripcion: 'Permitir exportar los casos a un archivo Excel',
    estado: 'nuevo',
    prioridad: 'baja',
    responsable: 'Lucía Fernández',
  },
  {
    id: uuidv4(),
    nombre: '🟨 Crear sistema de comentarios',
    descripcion: 'Permitir que los usuarios comenten en los casos',
    estado: 'nuevo',
    prioridad: 'media',
    responsable: undefined,
  },
  {
    id: uuidv4(),
    nombre: '🟫 Refactorizar lógica de negocio',
    descripcion: 'Simplificar y modularizar el código del backend',
    estado: 'en progreso',
    prioridad: 'alta',
    responsable: 'Miguel Ángel',
  },
  {
    id: uuidv4(),
    nombre: '⬛ Añadir logs de auditoría',
    descripcion: 'Registrar todas las acciones importantes de los usuarios',
    estado: 'nuevo',
    prioridad: 'media',
    responsable: undefined,
  },
  {
    id: uuidv4(),
    nombre: '⬜ Mejorar tiempos de carga',
    descripcion: 'Optimizar recursos estáticos y lazy loading',
    estado: 'en progreso',
    prioridad: 'baja',
    responsable: 'Elena Ruiz',
  },
];
